name: Create the DEB

permissions:
  contents: write

on:
  push:
    paths:
      - "mrmShared/linux/**"
    tags:
  pull_request:
    paths:
      - "mrmShared/linux/**"
  workflow_dispatch:

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: "apt-get install"
        run: |
          sudo apt-get update
          sudo apt-get -y install dkms debhelper gcc g++ libtool autoconf
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Build pakckage
        run: |
            cd REPO/mrmShared/linux
            dpkg-buildpackage
            cd dkms-rpm
            sudo make
      - name: Read VERSION file
        id: getversion
        run: echo "version=`cat REPO/mrmShared/linux/debian/changelog | grep mrf-dkms | head -n 1 | cut -f 2 -d '(' | cut -f 1 -d ')'`" >> $GITHUB_OUTPUT
      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: |
              REPO/mrmShared/mrf-dkms_${{ steps.getversion.outputs.version }}_all.deb
              REPO/mrmShared/linux/dkms-rpm/*.rpm
