name: Create deb and rpm package

permissions:
  contents: write

on:
  push:
    tags:
        - 'kd*'

jobs:
  Create_Packages:
    name: Create Packages
    runs-on: ubuntu-latest
    steps:
      - name: "apt-get install"
        run: |
          sudo apt-get update
          sudo apt-get -y install dkms debhelper
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Build packages
        run: |
            cd REPO/mrmShared/linux
            dpkg-buildpackage
            cd dkms-rpm
            make
      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: |
              REPO/mrmShared/*.deb
              REPO/mrmShared/linux/dkms-rpm/rpmbuild/RPMS/*/*.rpm
