name: Create the RPM

permissions:
  contents: write

on:
  push:
    tags:

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          cd REPO/mrmShared/linux/dkms-rpm
          make

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: REPO/mrmShared/linux/dkms-rpm/rpmbuild/RPMS/x86_64/*.rpm
